version: "3"
services:

    reverseproxy:
        build:
          context: ./Nginx
          dockerfile: Nginx.Dockerfile
        ports:
          - 80:80
          - 443:443
        restart: always
        command: [nginx-debug, '-g', 'daemon off;']
    
    api:
        build: .
        ports:
            - 5000:5000
        environment:
            ConnectionStrings__TechnikumDirektDatabase: Server=db,1433;Database=master;User Id=sa;Password=Greenmouse123;
            TestingUrls__TestingEnvUrl: localhost
            ASPNETCORE_ENVIRONMENT: Production
        depends_on:
            - reverseproxy
            - db

    db:
        image: mcr.microsoft.com/mssql/server:2017-latest
        environment:
            SA_PASSWORD: Greenmouse123
            ACCEPT_EULA: "Y"

    frontend:
        build:
            context: ./Services/TechnikumDirekt.Services/ClientApp
            dockerfile: Dockerfile
        ports:
            - 8081:80
        depends_on:
            - api