/*
 * Parcel Logistics Service
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace TechnikumDirekt.Services.Models
{
    /// <summary>
    /// </summary>
    [DataContract, JsonConverter(typeof(HopJsonConverter))]
    public class Hop
    {
        /// <summary>
        /// Gets or Sets HopType
        /// </summary>
        [Required]
        [DataMember(Name = "hopType")]
        public string HopType { get; set; }

        /// <summary>
        /// Unique CODE of the hop.
        /// </summary>
        /// <value>Unique CODE of the hop.</value>
        [Required]
        [DataMember(Name = "code")]
        public string Code { get; set; }

        /// <summary>
        /// Description of the hop.
        /// </summary>
        /// <value>Description of the hop.</value>
        [Required]
        [DataMember(Name = "description")]
        public string Description { get; set; }

        /// <summary>
        /// Delay processing takes on the hop.
        /// </summary>
        /// <value>Delay processing takes on the hop.</value>
        [Required]
        [DataMember(Name = "processingDelayMins")]
        public int? ProcessingDelayMins { get; set; }

        /// <summary>
        /// Name of the location (village, city, ..) of the hop.
        /// </summary>
        /// <value>Name of the location (village, city, ..) of the hop.</value>
        [Required]
        [DataMember(Name = "locationName")]
        public string LocationName { get; set; }

        /// <summary>
        /// Gets or Sets LocationCoordinates
        /// </summary>
        [Required]
        [DataMember(Name = "locationCoordinates")]
        public GeoCoordinate LocationCoordinates { get; set; }
    }

    public class HopJsonConverter : JsonCreationConverter<Hop>
    {
        protected override Hop Create(Type objectType, JObject jObject)
        {
            if (jObject == null) throw new ArgumentNullException("jObject");

            if (jObject["hopType"] != null && (string) jObject["hopType"] is var hopTypeString && hopTypeString != "")
            {
                if (hopTypeString == "Truck")
                {
                    return new Truck();
                }
                else if (hopTypeString == "Transferwarehouse")
                {
                    return new Transferwarehouse();
                } else
                {
                    return new Warehouse();
                }
            }

            return new Hop();
        }
    }
}