/*
 * Parcel Logistics Service
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;

namespace TechnikumDirekt.Services.Models
{
    /// <summary>
    /// </summary>
    [DataContract]
    public class Parcel
    {
        /// <summary>
        ///     Gets or Sets Weight
        /// </summary>
        [Required]
        [DataMember(Name = "weight")]
        public float? Weight { get; set; }

        /// <summary>
        ///     Gets or Sets Recipient
        /// </summary>
        [Required]
        [DataMember(Name = "recipient")]
        public Recipient Recipient { get; set; }

        /// <summary>
        ///     Gets or Sets Sender
        /// </summary>
        [Required]
        [DataMember(Name = "sender")]
        public Recipient Sender { get; set; }
    }
}