/*
 * Parcel Logistics Service
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.ComponentModel.DataAnnotations;

namespace TechnikumDirekt.DataAccess.Models
{
    /// <summary>
    /// n:m intermediate table for Parcel <-> Hop
    /// </summary>

    public class HopArrival
    {
        public string ParcelTrackingId { get; set; }
        public Parcel Parcel { get; set; }

        public string HopCode { get; set; }
        public Hop Hop { get; set; }

        /// <summary>
        ///     The date/time the parcel arrived at the hop.
        /// </summary>
        /// <value>The date/time the parcel arrived at the hop.</value>

        public DateTime? DateTime { get; set; }
    }
}