/*
 * Parcel Logistics Service
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.Runtime.Serialization;

namespace TechnikumDirekt.Services.Models
{
    /// <summary>
    /// </summary>
    [DataContract]
    public class WebhookMessage : TrackingInformation
    {
        /// <summary>
        ///     Gets or Sets TrackingId
        /// </summary>
        [DataMember(Name = "trackingId")]
        public string TrackingId { get; set; }
    }
}